name: SkyCraftSkyBlock
version: '${project.version}'
main: fr.sterll.skycraftskyblock.Main
api-version: 1.17
authors: [ Sterll ]

commands:
  is:
    aliases: island
    description: Permet de jouer au skyblock
